version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - '**/*' # Include all other application files
  base-directory: build
